# This workflow has been reverted to avoid conflicts with Netlify deployment
# The site is now deployed directly through Netlify as per the documentation

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    # Build step removed to avoid conflicts with Netlify deployment
    # Netlify will handle the build process as configured in netlify.toml